# Generated by Django 5.1 on 2024-09-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_rental', '0002_rename_specifications_bikemodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikemodel',
            name='fuel_system',
        ),
    ]
